name: Deploy Go Application to EC2

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy-staging:
    if: ${{ github.ref == 'refs/heads/staging' }} # Verifica si la rama es staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.3
        timeout-minutes: 30
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_STAGING }}
          command_timeout: 30m
          script: |
            cd ~/afrus-whatsapp-evolution_api-notification

            # 2. Update project
            git pull origin staging

            # 3. Build Docker image
            sudo docker build -t afrus-whatsapp-evolution_api-notification \
              --build-arg ENVIRONMENT="${{ secrets.ENVIRONMENT_STAGING }}" \
              --build-arg SERVER_PORT="${{ secrets.SERVER_PORT_STAGING }}" \
              --build-arg RABBITMQ_URL="${{ secrets.RABBITMQ_URL_STAGING }}" \
              --build-arg RABBITMQ_PORT="${{ secrets.RABBITMQ_PORT_STAGING }}" \
              --build-arg RABBITMQ_USER="${{ secrets.RABBITMQ_USER_STAGING }}" \
              --build-arg RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD_STAGING }}" \
              --build-arg RABBITMQ_MANAGER_PORT="${{ secrets.RABBITMQ_MANAGER_PORT_STAGING }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE_STAGING }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE_STAGING }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY_STAGING }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE_STAGING }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY_STAGING }}" \
              --build-arg RABBITMQ_BILLING_EXCHANGE="${{ secrets.RABBITMQ_BILLING_EXCHANGE_STAGING }}" \
              --build-arg RABBITMQ_BILLING_QUEUE="${{ secrets.RABBITMQ_BILLING_QUEUE_STAGING }}" \
              --build-arg RABBITMQ_BILLING_ROUTING_KEY="${{ secrets.RABBITMQ_BILLING_ROUTING_KEY_STAGING }}" \
              --build-arg AFRUS_DB_USER="${{ secrets.AFRUS_DB_USER_STAGING }}" \
              --build-arg AFRUS_DB_HOST="${{ secrets.AFRUS_DB_HOST_STAGING }}" \
              --build-arg AFRUS_DB_PORT="${{ secrets.AFRUS_DB_PORT_STAGING }}" \
              --build-arg AFRUS_DB_NAME="${{ secrets.AFRUS_DB_NAME_STAGING }}" \
              --build-arg AFRUS_DB_SSL_MODE="${{ secrets.AFRUS_DB_SSL_MODE_STAGING }}" \
              --build-arg AFRUS_DB_PASSWORD="${{ secrets.AFRUS_DB_PASSWORD_STAGING }}" \
              --build-arg EVENTS_DB_USER="${{ secrets.EVENTS_DB_USER_STAGING }}" \
              --build-arg EVENTS_DB_HOST="${{ secrets.EVENTS_DB_HOST_STAGING }}" \
              --build-arg EVENTS_DB_PORT="${{ secrets.EVENTS_DB_PORT_STAGING }}" \
              --build-arg EVENTS_DB_SSL_MODE="${{ secrets.EVENTS_DB_SSL_MODE_STAGING }}" \
              --build-arg EVENTS_DB_PASSWORD="${{ secrets.EVENTS_DB_PASSWORD_STAGING }}" \
              --build-arg EVENTS_DB_NAME="${{ secrets.EVENTS_DB_NAME_STAGING }}" \
              --build-arg EVOLUTION_API_BASE_URL="${{ secrets.EVOLUTION_API_BASE_URL_STAGING }}" \
              --build-arg EVOLUTION_API_KEY="${{ secrets.EVOLUTION_API_KEY_STAGING }}" \
              -f ./Dockerfile.prod .

            # 4. Stop and remove existing container 
            CONTAINER_ID=$(sudo docker ps -aqf "name=afrus-whatsapp-evolution_api-notification")
            if [ -n "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            # 4b. Restart nginx to free port 5000
            sudo systemctl restart nginx

            # 5. Run new container
            sudo docker run -d --name afrus-whatsapp-evolution_api-notification --network host \
              -e ENVIRONMENT="${{ secrets.ENVIRONMENT_STAGING }}" \
              -e SERVER_PORT="${{ secrets.SERVER_PORT_STAGING }}" \
              -e RABBITMQ_URL="${{ secrets.RABBITMQ_URL_STAGING }}" \
              -e RABBITMQ_PORT="${{ secrets.RABBITMQ_PORT_STAGING }}" \
              -e RABBITMQ_USER="${{ secrets.RABBITMQ_USER_STAGING}}" \
              -e RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD_STAGING }}" \
              -e RABBITMQ_MANAGER_PORT="${{ secrets.RABBITMQ_MANAGER_PORT_STAGING }}" \
              -e RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE_STAGING }}" \
              -e RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE_STAGING }}" \
              -e RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY_STAGING }}" \
              -e RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE_STAGING }}" \
              -e RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY_STAGING }}" \
              -e RABBITMQ_BILLING_EXCHANGE="${{ secrets.RABBITMQ_BILLING_EXCHANGE_STAGING }}" \
              -e RABBITMQ_BILLING_QUEUE="${{ secrets.RABBITMQ_BILLING_QUEUE_STAGING }}" \
              -e RABBITMQ_BILLING_ROUTING_KEY="${{ secrets.RABBITMQ_BILLING_ROUTING_KEY_STAGING }}" \
              -e AFRUS_DB_USER="${{ secrets.AFRUS_DB_USER_STAGING }}" \
              -e AFRUS_DB_HOST="${{ secrets.AFRUS_DB_HOST_STAGING }}" \
              -e AFRUS_DB_PORT="${{ secrets.AFRUS_DB_PORT_STAGING }}" \
              -e AFRUS_DB_NAME="${{ secrets.AFRUS_DB_NAME_STAGING }}" \
              -e AFRUS_DB_SSL_MODE="${{ secrets.AFRUS_DB_SSL_MODE_STAGING }}" \
              -e AFRUS_DB_PASSWORD="${{ secrets.AFRUS_DB_PASSWORD_STAGING }}" \
              -e EVENTS_DB_USER="${{ secrets.EVENTS_DB_USER_STAGING }}" \
              -e EVENTS_DB_HOST="${{ secrets.EVENTS_DB_HOST_STAGING }}" \
              -e EVENTS_DB_PORT="${{ secrets.EVENTS_DB_PORT_STAGING }}" \
              -e EVENTS_DB_SSL_MODE="${{ secrets.EVENTS_DB_SSL_MODE_STAGING }}" \
              -e EVENTS_DB_PASSWORD="${{ secrets.EVENTS_DB_PASSWORD_STAGING }}" \
              -e EVENTS_DB_NAME="${{ secrets.EVENTS_DB_NAME_STAGING }}" \
              -e EVOLUTION_API_BASE_URL="${{ secrets.EVOLUTION_API_BASE_URL_STAGING }}" \
              -e EVOLUTION_API_KEY="${{ secrets.EVOLUTION_API_KEY_STAGING }}" \
              afrus-whatsapp-evolution_api-notification

      - name: Send Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Pipeline de production ejecutado en el repositorio ${{ github.repository }} con el tag ${{ github.ref }} por el usuario ${{ github.event.head_commit.author.username }}."}' $DISCORD_WEBHOOK_URL
  
  deploy-main:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }} # Verifica si la rama es main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.3
        timeout-minutes: 30
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd ~/afrus-whatsapp-evolution_api-notification

            # 2. Update project
            git pull origin main

            # 3. Build Docker image
            sudo docker build -t afrus-whatsapp-evolution_api-notification \
              --build-arg ENVIRONMENT="${{ secrets.ENVIRONMENT }}" \
              --build-arg SERVER_PORT="${{ secrets.SERVER_PORT }}" \
              --build-arg RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
              --build-arg RABBITMQ_PORT="${{ secrets.RABBITMQ_PORT }}" \
              --build-arg RABBITMQ_USER="${{ secrets.RABBITMQ_USER }}" \
              --build-arg RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}" \
              --build-arg RABBITMQ_MANAGER_PORT="${{ secrets.RABBITMQ_MANAGER_PORT }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE }}" \
              --build-arg RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY }}" \
              --build-arg RABBITMQ_BILLING_EXCHANGE="${{ secrets.RABBITMQ_BILLING_EXCHANGE }}" \
              --build-arg RABBITMQ_BILLING_QUEUE="${{ secrets.RABBITMQ_BILLING_QUEUE }}" \
              --build-arg RABBITMQ_BILLING_ROUTING_KEY="${{ secrets.RABBITMQ_BILLING_ROUTING_KEY }}" \
              --build-arg AFRUS_DB_USER="${{ secrets.AFRUS_DB_USER }}" \
              --build-arg AFRUS_DB_HOST="${{ secrets.AFRUS_DB_HOST }}" \
              --build-arg AFRUS_DB_PORT="${{ secrets.AFRUS_DB_PORT }}" \
              --build-arg AFRUS_DB_NAME="${{ secrets.AFRUS_DB_NAME }}" \
              --build-arg AFRUS_DB_SSL_MODE="${{ secrets.AFRUS_DB_SSL_MODE }}" \
              --build-arg AFRUS_DB_PASSWORD="${{ secrets.AFRUS_DB_PASSWORD }}" \
              --build-arg EVENTS_DB_USER="${{ secrets.EVENTS_DB_USER }}" \
              --build-arg EVENTS_DB_HOST="${{ secrets.EVENTS_DB_HOST }}" \
              --build-arg EVENTS_DB_PORT="${{ secrets.EVENTS_DB_PORT }}" \
              --build-arg EVENTS_DB_SSL_MODE="${{ secrets.EVENTS_DB_SSL_MODE }}" \
              --build-arg EVENTS_DB_PASSWORD="${{ secrets.EVENTS_DB_PASSWORD }}" \
              --build-arg EVENTS_DB_NAME="${{ secrets.EVENTS_DB_NAME }}" \
              --build-arg EVOLUTION_API_BASE_URL="${{ secrets.EVOLUTION_API_BASE_URL }}" \
              --build-arg EVOLUTION_API_KEY="${{ secrets.EVOLUTION_API_KEY }}" \
              -f ./Dockerfile.prod .

            # 4. Stop and remove existing container 
            CONTAINER_ID=$(sudo docker ps -aqf "name=afrus-whatsapp-evolution_api-notification")
            if [ -n "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi

            # 4b. Restart nginx to free port 5000
            sudo systemctl restart nginx

            # 5. Run new container
            sudo docker run -d --name afrus-whatsapp-evolution_api-notification --network host \
            -e ENVIRONMENT="${{ secrets.ENVIRONMENT }}" \
            -e SERVER_PORT="${{ secrets.SERVER_PORT }}" \
            -e RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            -e RABBITMQ_PORT="${{ secrets.RABBITMQ_PORT }}" \
            -e RABBITMQ_USER="${{ secrets.RABBITMQ_USER}}" \
            -e RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}" \
            -e RABBITMQ_MANAGER_PORT="${{ secrets.RABBITMQ_MANAGER_PORT }}" \
            -e RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_EXCHANGE }}" \
            -e RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_QUEUE }}" \
            -e RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_BLAST_ROUTING_KEY }}" \
            -e RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_QUEUE }}" \
            -e RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY="${{ secrets.RABBITMQ_EVOLUTION_API_NOTIFICATION_AUTORESPONDER_ROUTING_KEY }}" \
            -e RABBITMQ_BILLING_EXCHANGE="${{ secrets.RABBITMQ_BILLING_EXCHANGE }}" \
            -e RABBITMQ_BILLING_QUEUE="${{ secrets.RABBITMQ_BILLING_QUEUE }}" \
            -e RABBITMQ_BILLING_ROUTING_KEY="${{ secrets.RABBITMQ_BILLING_ROUTING_KEY }}" \
            -e AFRUS_DB_USER="${{ secrets.AFRUS_DB_USER }}" \
            -e AFRUS_DB_HOST="${{ secrets.AFRUS_DB_HOST }}" \
            -e AFRUS_DB_PORT="${{ secrets.AFRUS_DB_PORT }}" \
            -e AFRUS_DB_NAME="${{ secrets.AFRUS_DB_NAME }}" \
            -e AFRUS_DB_SSL_MODE="${{ secrets.AFRUS_DB_SSL_MODE }}" \
            -e AFRUS_DB_PASSWORD="${{ secrets.AFRUS_DB_PASSWORD }}" \
            -e EVENTS_DB_USER="${{ secrets.EVENTS_DB_USER }}" \
            -e EVENTS_DB_HOST="${{ secrets.EVENTS_DB_HOST }}" \
            -e EVENTS_DB_PORT="${{ secrets.EVENTS_DB_PORT }}" \
            -e EVENTS_DB_SSL_MODE="${{ secrets.EVENTS_DB_SSL_MODE }}" \
            -e EVENTS_DB_PASSWORD="${{ secrets.EVENTS_DB_PASSWORD }}" \
            -e EVENTS_DB_NAME="${{ secrets.EVENTS_DB_NAME }}" \
            -e EVOLUTION_API_BASE_URL="${{ secrets.EVOLUTION_API_BASE_URL }}" \
            -e EVOLUTION_API_KEY="${{ secrets.EVOLUTION_API_KEY }}" \
            afrus-whatsapp-evolution_api-notification

      - name: Send Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"content": "Pipeline de production ejecutado en el repositorio ${{ github.repository }} con el tag ${{ github.ref }} por el usuario ${{ github.event.head_commit.author.username }}."}' $DISCORD_WEBHOOK_URL
